### ISSUE TITLE
今后是否会考虑增加添加文件备注功能呢？

### ISSUE THREAD

**Issue by GalensGan** [x7890/FolderComments#1]
用起来很便捷，希望可以支持对文件的备注，这样就完美了。

**Comment by x7890** [comment]
很抱歉，因为这个给文件夹添加备注的原理，其实只是把Windows的一个隐藏功能挖掘出来。Windows规定文件夹备注储存在desktop.ini中，并且会自动读取，因此移动文件夹或给文件夹改名，备注不会丢失，我认为这很重要。对于文件的备注，Windows利用“元数据”储存额外信息实现文件的备注功能（我没有验证过该说法的真实性，不过要想给txt等纯文本文件添加备注，必然只能额外储存备注信息），只不过一样默认没有显示。File Meta一类的软件挖掘了这一功能，备注效果很好，当然需要使用NTFS文件系统的磁盘。有一些资源管理器（如Total Commander）也自己维护了额外的备注文件。如果自己维护备注，可能需要编写插件等，此工作量对我来说无法做到。有些特殊的文件（如视频、PDF等）的备注以不同的方式储存在文件本身中，移动文件不会丢失备注。但修改备注可能引起原始文件变化（不太安全）；对于PDF等文件，甚至可能不允许修改其备注信息。若能够查找到相关资料，我可能会考虑逐步实现最后一种支持文件类型可能十分有限但较可靠的方法。

**Comment by GalensGan** [comment]
谢谢您的回复，了解了。

**Comment by GalensGan** [comment]
> 很抱歉，因为这个给文件夹添加备注的原理，其实只是把Windows的一个隐藏功能挖掘出来。Windows规定文件夹备注储存在desktop.ini中，并且会自动读取，因此移动文件夹或给文件夹改名，备注不会丢失，我认为这很重要。对于文件的备注，Windows利用“元数据”储存额外信息实现文件的备注功能（我没有验证过该说法的真实性，不过要想给txt等纯文本文件添加备注，必然只能额外储存备注信息），只不过一样默认没有显示。File Meta一类的软件挖掘了这一功能，备注效果很好，当然需要使用NTFS文件系统的磁盘。有一些资源管理器（如Total Commander）也自己维护了额外的备注文件。如果自己维护备注，可能需要编写插件等，此工作量对我来说无法做到。有些特殊的文件（如视频、PDF等）的备注以不同的方式储存在文件本身中，移动文件不会丢失备注。但修改备注可能引起原始文件变化（不太安全）；对于PDF等文件，甚至可能不允许修改其备注信息。若能够查找到相关资料，我可能会考虑逐步实现最后一种支持文件类型可能十分有限但较可靠的方法。

谢谢您的回复，了解了。
