### ISSUE TITLE
程序体积小使用方便完美解决问题，提个建议

### ISSUE THREAD

**Issue by AstroboyPlus** [x7890/FolderComments#3]
在添加完备注后，文件夹的修改时间会变成当前时间，这个能让他不改变吗？

**Comment by AstroboyPlus** [comment]
@x7890

**Comment by x7890** [comment]
已经修改为新版本：编辑备注后，自动将文件夹的修改日期重置为编辑框中的日期，默认使用编辑备注前的日期，也可以手动改变。
